export const SELECT = 'select'
export const LISTEN = 'listen'
export const SEARCH = 'search'
export const COLLECT = 'collect'
export const REMOVE = 'remove'
export const GETSTORAGE = 'getstorage'
export const UPLOAD = 'upload'
export const FILTE = 'filte'